# Generated by Django 3.1.4 on 2020-12-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dayily',
            fields=[
                ('ts_code', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('area', models.CharField(blank=True, max_length=10, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('list_date', models.TextField(blank=True, null=True)),
                ('new_date', models.TextField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('pre_close', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('pct_chg', models.FloatField(blank=True, null=True)),
                ('vol', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('trade_date', models.TextField(blank=True, null=True)),
                ('buy_sm_vol', models.BigIntegerField(blank=True, null=True)),
                ('buy_sm_amount', models.FloatField(blank=True, null=True)),
                ('sell_sm_vol', models.BigIntegerField(blank=True, null=True)),
                ('sell_sm_amount', models.FloatField(blank=True, null=True)),
                ('buy_md_vol', models.BigIntegerField(blank=True, null=True)),
                ('buy_md_amount', models.FloatField(blank=True, null=True)),
                ('sell_md_vol', models.BigIntegerField(blank=True, null=True)),
                ('sell_md_amount', models.FloatField(blank=True, null=True)),
                ('buy_lg_vol', models.BigIntegerField(blank=True, null=True)),
                ('buy_lg_amount', models.FloatField(blank=True, null=True)),
                ('sell_lg_vol', models.BigIntegerField(blank=True, null=True)),
                ('sell_lg_amount', models.FloatField(blank=True, null=True)),
                ('buy_elg_vol', models.BigIntegerField(blank=True, null=True)),
                ('buy_elg_amount', models.FloatField(blank=True, null=True)),
                ('sell_elg_vol', models.BigIntegerField(blank=True, null=True)),
                ('sell_elg_amount', models.FloatField(blank=True, null=True)),
                ('net_mf_vol', models.BigIntegerField(blank=True, null=True)),
                ('net_mf_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dayily',
                'db_table': 'Dayily',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ts_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Stock',
                'db_table': 'stock',
                'ordering': ['ts_code'],
            },
        ),
    ]
