# Generated by Django 3.1.4 on 2020-12-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayily',
            name='new_date',
        ),
        migrations.RemoveField(
            model_name='dayily',
            name='symbol',
        ),
        migrations.AddField(
            model_name='dayily',
            name='circ_mv',
            field=models.FloatField(blank=True, null=True, verbose_name='流通市值'),
        ),
        migrations.AddField(
            model_name='dayily',
            name='dv_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='股息率'),
        ),
        migrations.AddField(
            model_name='dayily',
            name='float_share',
            field=models.FloatField(blank=True, null=True, verbose_name='流通股本'),
        ),
        migrations.AddField(
            model_name='dayily',
            name='free_share',
            field=models.FloatField(blank=True, null=True, verbose_name='自由流通股本'),
        ),
        migrations.AddField(
            model_name='dayily',
            name='pb',
            field=models.FloatField(blank=True, null=True, verbose_name='市净率'),
        ),
        migrations.AddField(
            model_name='dayily',
            name='pe',
            field=models.FloatField(blank=True, null=True, verbose_name='市盈率'),
        ),
        migrations.AddField(
            model_name='dayily',
            name='ps',
            field=models.FloatField(blank=True, null=True, verbose_name='市销率'),
        ),
        migrations.AddField(
            model_name='dayily',
            name='total_mv',
            field=models.FloatField(blank=True, null=True, verbose_name='总市值'),
        ),
        migrations.AddField(
            model_name='dayily',
            name='total_share',
            field=models.FloatField(blank=True, null=True, verbose_name='总股本'),
        ),
        migrations.AddField(
            model_name='dayily',
            name='turnover_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='换手率(%)'),
        ),
        migrations.AddField(
            model_name='dayily',
            name='volume_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='量比'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='成交额(千元)'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='area',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='所在地域'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='buy_elg_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='特大单买入金额'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='buy_elg_vol',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='特大单买入量'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='buy_lg_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='大单买入金额'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='buy_lg_vol',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='大单买入量'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='buy_md_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='中单买入金额'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='buy_md_vol',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='中单买入量'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='buy_sm_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='小单买入金额'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='buy_sm_vol',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='小单买入量'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='change',
            field=models.FloatField(blank=True, null=True, verbose_name='涨跌额'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='close',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘价'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='high',
            field=models.FloatField(blank=True, null=True, verbose_name='最高价'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='industry',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='list_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='上市日期'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='low',
            field=models.FloatField(blank=True, null=True, verbose_name='最低价'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='股票名称'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='net_mf_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='净流入额'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='net_mf_vol',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='净流入量'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='open',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘价'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='pct_chg',
            field=models.FloatField(blank=True, null=True, verbose_name='涨跌幅'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='pre_close',
            field=models.FloatField(blank=True, null=True, verbose_name='昨收价'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='sell_elg_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='特大单卖出金额'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='sell_elg_vol',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='特大单卖出量'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='sell_lg_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='大单卖出金额'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='sell_lg_vol',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='大单卖出量'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='sell_md_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='中单卖出金额'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='sell_md_vol',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='中单卖出量'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='sell_sm_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='小单卖出金额'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='sell_sm_vol',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='小单卖出量'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='trade_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='ts_code',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='vol',
            field=models.FloatField(blank=True, null=True, verbose_name='成交量(手)'),
        ),
    ]
