# Generated by Django 3.1.4 on 2020-12-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websec', '0002_auto_20201205_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayily',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所在地域'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='股票名称'),
        ),
    ]
