# Generated by Django 3.1.4 on 2020-12-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websec', '0003_auto_20201205_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayily',
            name='industry',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='list_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='上市日期'),
        ),
        migrations.AlterField(
            model_name='dayily',
            name='trade_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='交易日期'),
        ),
    ]
