# Generated by Django 3.1.4 on 2020-12-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websec', '0004_auto_20201205_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayily',
            name='is_hs',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='是否沪深港通标的'),
        ),
        migrations.AddField(
            model_name='dayily',
            name='market',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='市场类型'),
        ),
    ]
