# Generated by Django 2.2 on 2020-10-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=25, verbose_name='标题')),
                ('mold', models.CharField(choices=[('0', '招室友'), ('1', '找房子')], default='', max_length=25, verbose_name='类型')),
                ('addr', models.CharField(default='', max_length=25, verbose_name='位置')),
                ('size', models.CharField(default='', max_length=25, verbose_name='房间大小')),
                ('orientation', models.CharField(default='', max_length=25, verbose_name='朝向')),
                ('estate', models.CharField(default='', max_length=25, verbose_name='所在小区')),
                ('rent', models.CharField(default='', max_length=25, verbose_name='租金')),
                ('payment', models.CharField(default='', max_length=25, verbose_name='付款方式')),
                ('public_facilities', models.CharField(default='', max_length=25, verbose_name='公共设施')),
                ('details', models.TextField(default='此人很懒，什么也没有留下------------', max_length=1024, verbose_name='房屋描述')),
                ('images', models.ImageField(upload_to='', verbose_name='图片')),
            ],
            options={
                'db_table': 'Rent',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
    ]
